spring:
  application:
    name: travel-forex-spring
  datasource:
    url: jdbc:mariadb://localhost:8012/travel
    username: travel_user
    password: travel
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: yfOxDwK6iUAMgqxeWypyhOlft9wXLv8ZCV4GuH76Ii4EoxE7uAu7XMguSA2DJmpH
  expiration: 86400000 # 24시간